version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./server:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        container_name: php
        build: ./docker/php
        depends_on:
            - db
            - db-testing
            - mailhog
        volumes:
            - ./server:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    db:
        image: mysql:5.7
        container_name: db-host
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/mysql/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    db-testing:
        image: mysql:5.7
        container_name: db-test-host
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - db-store:/var/lib/mysql
            - ./logs:/var/log/mysql
        tmpfs:
            /var/lib/mysql
            /var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            TZ: 'Asia/Tokyo'
        ports:
            - 3307:3306

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

volumes:
    db-store: